version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    ports:
      - 5432:5432
    networks:
      - keycloak-network
  keyckoak:
    image: bitnami/keycloak:latest
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
    networks:
      - keycloak-network
    depends_on:
      - postgres

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
